name: virtual_fitting_room
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  image_picker: ^0.8.5+3 #this is for image use
  image: ^3.0.8
  url_launcher: ^6.0.12 #for url launching
  onnxruntime: 1.4.1 #onnx interpreter
  share_plus:
  camera:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/model.onnx #needed to use model